'use client';
import { useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '@/lib/supabase';
import toast from 'react-hot-toast';
import { FiEdit2, FiTrash2, FiSave, FiX, FiSearch, FiRefreshCw, FiChevronLeft, FiChevronRight, FiPhone, FiCheckCircle } from 'react-icons/fi';
import { RecordModal, VisitModal, AllergyModal, ContactModal } from './modals';
const G = { red:'linear-gradient(135deg,#ef4444,#dc2626)', green:'linear-gradient(135deg,#059669,#0d9488)', amber:'linear-gradient(135deg,#f59e0b,#d97706)', blue:'linear-gradient(135deg,#2563eb,#3b82f6)', purple:'linear-gradient(135deg,#7c3aed,#8b5cf6)' };

export default function StudentHealthPage() {
  const [loading,setLoading]=useState(true),[students,setStudents]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]),
    [allergies,setAllergies]=useState<any[]>([]),[visits,setVisits]=useState<any[]>([]),[contacts,setContacts]=useState<any[]>([]),
    [saving,setSaving]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1),
    [tab,setTab]=useState<'records'|'visits'|'emergency'>('records'),[showModal,setShowModal]=useState(''),[editRec,setEditRec]=useState<any>(null);
  const [recForm,setRecForm]=useState({student_id:0,blood_group:'',genotype:'',height_cm:'',weight_kg:'',vision_left:'',vision_right:'',chronic_conditions:'',allergies_text:'',current_medications:'',disability_notes:''});
  const [visitForm,setVisitForm]=useState({student_id:0,complaint:'',diagnosis:'',treatment:'',medication_given:'',temperature:'',blood_pressure:'',referred_to:'',attended_by:'',notes:''});
  const [allergyForm,setAllergyForm]=useState({student_id:0,allergen:'',severity:'mild',reaction:'',management_plan:''});
  const [contactForm,setContactForm]=useState({student_id:0,contact_name:'',relationship:'',phone:'',alt_phone:'',email:'',is_primary:false,escalation_order:1,can_authorize_treatment:false});

  const fetchAll=useCallback(async()=>{setLoading(true);const[s,r,a,v,c]=await Promise.all([supabase.from('school_students').select('id,first_name,last_name,admission_number,form_id').eq('is_active',true).order('last_name'),supabase.from('school_health_records').select('*'),supabase.from('school_health_allergies').select('*'),supabase.from('school_clinic_visits').select('*').order('visit_date',{ascending:false}),supabase.from('school_emergency_contacts').select('*').order('escalation_order')]);setStudents(s.data||[]);setRecords(r.data||[]);setAllergies(a.data||[]);setVisits(v.data||[]);setContacts(c.data||[]);setLoading(false)},[]);
  useEffect(()=>{fetchAll()},[fetchAll]);
  const getSt=(id:number)=>students.find(s=>s.id===id),getRec=(sid:number)=>records.find(r=>r.student_id===sid);
  const filtered=useMemo(()=>{if(!search)return students;const q=search.toLowerCase();return students.filter(s=>(s.last_name+s.first_name+s.admission_number).toLowerCase().includes(q))},[students,search]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/10)),paged=filtered.slice((page-1)*10,page*10);
  const severeAllergies=allergies.filter(a=>a.severity==='severe'||a.severity==='life_threatening');
  const thisMonthVisits=visits.filter(v=>{const d=new Date(v.visit_date),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()});

  const openRecordModal=(sid:number)=>{const rec=getRec(sid);setEditRec(rec||null);setRecForm({student_id:sid,blood_group:rec?.blood_group||'',genotype:rec?.genotype||'',height_cm:rec?.height_cm||'',weight_kg:rec?.weight_kg||'',vision_left:rec?.vision_left||'',vision_right:rec?.vision_right||'',chronic_conditions:rec?.chronic_conditions||'',allergies_text:rec?.allergies||'',current_medications:rec?.current_medications||'',disability_notes:rec?.disability_notes||''});setShowModal('record')};
  const saveRecord=async()=>{if(!recForm.student_id)return toast.error('Select a student');setSaving(true);try{const p={student_id:recForm.student_id,blood_group:recForm.blood_group||null,genotype:recForm.genotype||null,height_cm:recForm.height_cm?Number(recForm.height_cm):null,weight_kg:recForm.weight_kg?Number(recForm.weight_kg):null,vision_left:recForm.vision_left||null,vision_right:recForm.vision_right||null,chronic_conditions:recForm.chronic_conditions||null,allergies:recForm.allergies_text||null,current_medications:recForm.current_medications||null,disability_notes:recForm.disability_notes||null};let err;if(editRec?.id)({error:err}=await supabase.from('school_health_records').update(p).eq('id',editRec.id));else({error:err}=await supabase.from('school_health_records').insert([p]));if(err)throw err;toast.success('✅ Saved!');setShowModal('');fetchAll()}catch(e:any){toast.error(e.message)}setSaving(false)};
  const saveVisit=async()=>{if(!visitForm.student_id||!visitForm.complaint.trim())return toast.error('Student & complaint required');setSaving(true);const{error}=await supabase.from('school_clinic_visits').insert([{student_id:visitForm.student_id,complaint:visitForm.complaint.trim(),diagnosis:visitForm.diagnosis.trim()||null,treatment:visitForm.treatment.trim()||null,medication_given:visitForm.medication_given.trim()||null,temperature:visitForm.temperature?Number(visitForm.temperature):null,blood_pressure:visitForm.blood_pressure.trim()||null,referred_to:visitForm.referred_to.trim()||null,attended_by:visitForm.attended_by.trim()||null,notes:visitForm.notes.trim()||null}]);if(error)toast.error(error.message);else{toast.success('✅ Visit recorded!');setShowModal('');fetchAll()}setSaving(false)};
  const saveAllergy=async()=>{if(!allergyForm.student_id||!allergyForm.allergen.trim())return toast.error('Student & allergen required');setSaving(true);const{error}=await supabase.from('school_health_allergies').insert([{student_id:allergyForm.student_id,allergen:allergyForm.allergen.trim(),severity:allergyForm.severity,reaction:allergyForm.reaction.trim()||null,management_plan:allergyForm.management_plan.trim()||null}]);if(error)toast.error(error.message);else{toast.success('✅ Allergy added!');setShowModal('');fetchAll()}setSaving(false)};
  const saveContact=async()=>{if(!contactForm.student_id||!contactForm.contact_name.trim()||!contactForm.phone.trim())return toast.error('Student, name & phone required');setSaving(true);const{error}=await supabase.from('school_emergency_contacts').insert([{student_id:contactForm.student_id,contact_name:contactForm.contact_name.trim(),relationship:contactForm.relationship.trim()||null,phone:contactForm.phone.trim(),alt_phone:contactForm.alt_phone.trim()||null,email:contactForm.email.trim()||null,is_primary:contactForm.is_primary,escalation_order:contactForm.escalation_order,can_authorize_treatment:contactForm.can_authorize_treatment}]);if(error)toast.error(error.message);else{toast.success('✅ Contact added!');setShowModal('');fetchAll()}setSaving(false)};
  const delVisit=async(id:number)=>{if(!confirm('Delete?'))return;const{error}=await supabase.from('school_clinic_visits').delete().eq('id',id);if(!error){toast.success('Deleted');fetchAll()}};
  const delAllergy=async(id:number)=>{if(!confirm('Delete?'))return;const{error}=await supabase.from('school_health_allergies').delete().eq('id',id);if(!error){toast.success('Deleted');fetchAll()}};
  const delContact=async(id:number)=>{if(!confirm('Delete?'))return;const{error}=await supabase.from('school_emergency_contacts').delete().eq('id',id);if(!error){toast.success('Deleted');fetchAll()}};

  if(loading)return(<div className="flex flex-col items-center justify-center h-64 gap-3"><div className="w-12 h-12 rounded-2xl flex items-center justify-center text-2xl" style={{background:G.red}}>🏥</div><p className="text-sm font-bold text-gray-500">Loading Health Records…</p></div>);

  return (<div className="animate-fadeIn space-y-5">
    {/* HEADER + KPIS + TABS */}
    <div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-extrabold text-gray-900" style={{fontFamily:'Outfit,sans-serif',letterSpacing:'-0.03em'}}>🏥 Student Health Records</h1><p className="text-sm text-gray-500 mt-1">{records.length} records · {visits.length} visits · {allergies.length} allergies</p></div><div className="flex items-center gap-2 flex-wrap"><button onClick={fetchAll} className="p-2.5 rounded-xl border border-gray-200 text-gray-400 hover:text-red-600 transition"><FiRefreshCw size={15}/></button><button onClick={()=>{setShowModal('visit');setVisitForm({student_id:0,complaint:'',diagnosis:'',treatment:'',medication_given:'',temperature:'',blood_pressure:'',referred_to:'',attended_by:'',notes:''})}} className="px-4 py-2.5 rounded-xl text-sm font-bold" style={{background:'#f0fdf4',color:'#15803d',border:'none',cursor:'pointer'}}>🩺 Clinic Visit</button><button onClick={()=>{setShowModal('allergy');setAllergyForm({student_id:0,allergen:'',severity:'mild',reaction:'',management_plan:''})}} className="px-4 py-2.5 rounded-xl text-sm font-bold" style={{background:'#fffbeb',color:'#b45309',border:'none',cursor:'pointer'}}>⚠️ Allergy</button><button onClick={()=>{setShowModal('contact');setContactForm({student_id:0,contact_name:'',relationship:'',phone:'',alt_phone:'',email:'',is_primary:false,escalation_order:1,can_authorize_treatment:false})}} className="px-4 py-2.5 rounded-xl text-sm font-bold" style={{background:'#eff6ff',color:'#1d4ed8',border:'none',cursor:'pointer'}}>🆘 Emergency</button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[{l:'Health Records',v:records.length,e:'📋',c:'#ef4444'},{l:'Severe Allergies',v:severeAllergies.length,e:'⚠️',c:'#f59e0b'},{l:'Clinic Visits',v:visits.length,e:'🩺',c:'#059669'},{l:'This Month',v:thisMonthVisits.length,e:'📅',c:'#2563eb'},{l:'Emergency Contacts',v:contacts.length,e:'🆘',c:'#7c3aed'}].map((cd,i)=>(<div key={i} className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm hover:shadow-md transition-all relative overflow-hidden" style={{borderLeftWidth:4,borderLeftColor:cd.c}}><div className="flex items-center justify-between mb-2"><p className="text-[10px] font-bold text-gray-400 tracking-wider uppercase">{cd.l}</p><span className="text-xl">{cd.e}</span></div><p className="text-xl font-extrabold text-gray-900">{cd.v}</p><div className="absolute -bottom-6 -right-6 w-20 h-20 rounded-full opacity-[0.06]" style={{background:cd.c}}/></div>))}</div>
    <div className="flex gap-1 p-1 bg-gray-100 rounded-xl w-fit">{[{k:'records',l:'📋 Records'},{k:'visits',l:'🩺 Visits'},{k:'emergency',l:'🆘 Emergency'}].map(t=>(<button key={t.k} onClick={()=>setTab(t.k as any)} className={`px-4 py-2 rounded-lg text-xs font-bold transition-all ${tab===t.k?'bg-white shadow text-red-700':'text-gray-500 hover:text-gray-700'}`}>{t.l}</button>))}</div>

    {tab==='records'&&<><div className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm"><div className="flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-[220px]"><FiSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search students…" className="w-full pl-10 pr-9 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:bg-white focus:border-red-300"/>{search&&<button onClick={()=>{setSearch('');setPage(1)}} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-300 hover:text-gray-500"><FiX size={14}/></button>}</div><p className="ml-auto text-xs font-bold text-gray-400">{filtered.length} students</p></div></div>
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full border-collapse" style={{fontSize:12}}><thead><tr>{['#','Student','Blood','Allergies','Conditions','Emergency','⚙️'].map((h,i)=><th key={i} className="text-left px-3 py-3 text-[10px] font-bold uppercase tracking-wider whitespace-nowrap" style={{background:'#f8fafc',color:'#475569',borderBottom:'2px solid #e2e8f0'}}>{h}</th>)}</tr></thead>
    <tbody>{paged.map((st,idx)=>{const rec=getRec(st.id),stuA=allergies.filter(a=>a.student_id===st.id),stuC=contacts.filter(c=>c.student_id===st.id).sort((a,b)=>a.escalation_order-b.escalation_order);return(<tr key={st.id} style={{borderBottom:'1px solid #f1f5f9'}} onMouseEnter={e=>(e.currentTarget as HTMLTableRowElement).style.background='#fafbff'} onMouseLeave={e=>(e.currentTarget as HTMLTableRowElement).style.background=''}><td className="px-3 py-3 text-center font-bold text-gray-400">{(page-1)*10+idx+1}</td><td className="px-3 py-3"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold text-white" style={{background:G.purple}}>{(st.first_name?.[0]||'')+(st.last_name?.[0]||'')}</div><div><p className="font-bold text-gray-900">{st.last_name}, {st.first_name}</p><p className="text-[10px] text-gray-400">{st.admission_number}</p></div></div></td><td className="px-3 py-3 whitespace-nowrap">{rec?.blood_group?<span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-red-50 text-red-700 border border-red-200">🩸 {rec.blood_group}</span>:<span className="text-gray-300 text-[10px]">—</span>}</td><td className="px-3 py-3">{stuA.length>0?<div className="flex flex-wrap gap-1">{stuA.slice(0,3).map(a=><span key={a.id} className={`px-1.5 py-0.5 rounded text-[9px] font-bold ${a.severity==='severe'||a.severity==='life_threatening'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{a.allergen}</span>)}{stuA.length>3&&<span className="text-[9px] text-gray-400">+{stuA.length-3}</span>}</div>:<span className="text-green-500 text-[10px] font-bold">✅ None</span>}</td><td className="px-3 py-3"><p className="text-[10px] font-bold text-gray-700 line-clamp-2" style={{maxWidth:160}}>{rec?.chronic_conditions||'—'}</p></td><td className="px-3 py-3">{stuC[0]?<div><p className="text-[10px] font-bold text-blue-700">{stuC[0].contact_name}</p><a href={`tel:${stuC[0].phone}`} className="text-[9px] text-blue-500 hover:underline flex items-center gap-1"><FiPhone size={8}/>{stuC[0].phone}</a></div>:<span className="text-gray-300 text-[10px]">—</span>}</td><td className="px-3 py-3"><button onClick={()=>openRecordModal(st.id)} className="p-2 rounded-xl transition hover:scale-110" style={{background:'#ddd6fe',color:'#6d28d9'}}><FiEdit2 size={12}/></button></td></tr>);})}</tbody></table></div>
    {filtered.length>10&&<div className="px-5 py-3 bg-gray-50 border-t border-gray-100 flex items-center justify-between"><p className="text-xs text-gray-400">Page {page} of {totalPages}</p><div className="flex items-center gap-1.5"><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} className="p-2 rounded-xl border border-gray-200 text-gray-500 hover:bg-gray-100 disabled:opacity-30"><FiChevronLeft size={14}/></button><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} className="p-2 rounded-xl border border-gray-200 text-gray-500 hover:bg-gray-100 disabled:opacity-30"><FiChevronRight size={14}/></button></div></div>}</div></>}

    {tab==='visits'&&<div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full border-collapse" style={{fontSize:12}}><thead><tr>{['Date','Student','Complaint','Diagnosis','Treatment','Temp','By','Del'].map((h,i)=><th key={i} className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-wider" style={{background:'#f8fafc',color:'#475569',borderBottom:'2px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{visits.slice(0,30).map(v=>{const st=getSt(v.student_id);return(<tr key={v.id} style={{borderBottom:'1px solid #f1f5f9'}}><td className="px-4 py-3 text-xs font-bold text-gray-600">{new Date(v.visit_date).toLocaleDateString()}</td><td className="px-4 py-3 font-bold text-gray-900">{st?`${st.last_name}, ${st.first_name}`:'-'}</td><td className="px-4 py-3 text-gray-700" style={{maxWidth:200}}><p className="line-clamp-2">{v.complaint}</p></td><td className="px-4 py-3 text-gray-600" style={{maxWidth:160}}>{v.diagnosis||'-'}</td><td className="px-4 py-3 text-gray-600" style={{maxWidth:160}}>{v.treatment||'-'}</td><td className="px-4 py-3 text-xs text-gray-500">{v.temperature?`${v.temperature}C`:'-'}</td><td className="px-4 py-3 text-xs text-gray-500">{v.attended_by||'-'}</td><td className="px-4 py-3"><button onClick={()=>delVisit(v.id)} className="p-1.5 rounded-lg text-gray-300 hover:text-red-500"><FiTrash2 size={11}/></button></td></tr>);})}</tbody></table></div>{visits.length===0&&<div className="text-center py-12 text-gray-400"><span className="text-4xl block mb-2">🩺</span><p>No clinic visits yet</p></div>}</div>}

    {tab==='emergency'&&<div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full border-collapse" style={{fontSize:12}}><thead><tr>{['Student','Contact','Phone','Relationship','Priority','Auth','Del'].map((h,i)=><th key={i} className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-wider" style={{background:'#f8fafc',color:'#475569',borderBottom:'2px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{contacts.map(c=>{const st=getSt(c.student_id);return(<tr key={c.id} style={{borderBottom:'1px solid #f1f5f9'}}><td className="px-4 py-3 font-bold text-gray-900">{st?`${st.last_name}, ${st.first_name}`:'-'}</td><td className="px-4 py-3 font-semibold text-gray-800">{c.contact_name}{c.is_primary&&<span className="ml-1 px-1.5 py-0.5 rounded text-[8px] font-bold bg-blue-50 text-blue-700">PRIMARY</span>}</td><td className="px-4 py-3"><a href={`tel:${c.phone}`} className="text-blue-600 font-bold hover:underline flex items-center gap-1"><FiPhone size={10}/>{c.phone}</a></td><td className="px-4 py-3 text-gray-600">{c.relationship||'-'}</td><td className="px-4 py-3 text-center"><span className={`w-6 h-6 rounded-full inline-flex items-center justify-center text-[10px] font-bold ${c.escalation_order===1?'bg-red-50 text-red-700':'bg-gray-50 text-gray-600'}`}>{c.escalation_order}</span></td><td className="px-4 py-3">{c.can_authorize_treatment?<FiCheckCircle size={14} className="text-green-500"/>:<span className="text-gray-300">-</span>}</td><td className="px-4 py-3"><button onClick={()=>delContact(c.id)} className="p-1.5 rounded-lg text-gray-300 hover:text-red-500"><FiTrash2 size={11}/></button></td></tr>);})}</tbody></table></div>{contacts.length===0&&<div className="text-center py-12 text-gray-400"><span className="text-4xl block mb-2">🆘</span><p>No emergency contacts yet</p></div>}</div>}

    <RecordModal show={showModal==='record'} saving={saving} onClose={()=>setShowModal('')} onSave={saveRecord} form={recForm} setForm={setRecForm} students={students}/>
    <VisitModal show={showModal==='visit'} saving={saving} onClose={()=>setShowModal('')} onSave={saveVisit} form={visitForm} setForm={setVisitForm} students={students}/>
    <AllergyModal show={showModal==='allergy'} saving={saving} onClose={()=>setShowModal('')} onSave={saveAllergy} form={allergyForm} setForm={setAllergyForm} students={students}/>
    <ContactModal show={showModal==='contact'} saving={saving} onClose={()=>setShowModal('')} onSave={saveContact} form={contactForm} setForm={setContactForm} students={students}/>
  </div>);
}
