'use client';
import { useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '@/lib/supabase';
import toast from 'react-hot-toast';
import { FiSend, FiFileText, FiCheck, FiX, FiSearch, FiRefreshCw, FiChevronLeft, FiChevronRight, FiDownload, FiPhone, FiMail, FiMessageCircle } from 'react-icons/fi';
const G={blue:'linear-gradient(135deg,#2563eb,#3b82f6)',green:'linear-gradient(135deg,#059669,#0d9488)',amber:'linear-gradient(135deg,#f59e0b,#d97706)',purple:'linear-gradient(135deg,#7c3aed,#8b5cf6)',red:'linear-gradient(135deg,#ef4444,#dc2626)'};

export default function DigitalDeliveryPage() {
  const [loading,setLoading]=useState(true),[deliveries,setDeliveries]=useState<any[]>([]),
    [students,setStudents]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[examTypes,setExamTypes]=useState<any[]>([]),
    [saving,setSaving]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1),
    [tab,setTab]=useState<'deliveries'|'generate'>('deliveries'),[showModal,setShowModal]=useState('');
  const [genForm,setGenForm]=useState({term_id:0,exam_type_id:0,student_ids:[] as number[],channel:'all'});

  const fetchAll=useCallback(async()=>{setLoading(true);const[d,s,t,e]=await Promise.all([supabase.from('school_report_card_deliveries').select('*,school_students(first_name,last_name,admission_number)').order('created_at',{ascending:false}),supabase.from('school_students').select('id,first_name,last_name,admission_number').eq('status','Active').order('last_name'),supabase.from('school_terms').select('*').order('year',{ascending:false}),supabase.from('school_exam_types').select('*').eq('is_active',true)]);setDeliveries(d.data||[]);setStudents(s.data||[]);setTerms(t.data||[]);setExamTypes(e.data||[]);setLoading(false)},[]);
  useEffect(()=>{fetchAll()},[fetchAll]);

  const filtered=useMemo(()=>{if(!search)return deliveries;const q=search.toLowerCase();return deliveries.filter(d=>{const sn=d.school_students?`${d.school_students.last_name} ${d.school_students.first_name}`:'';return sn.toLowerCase().includes(q)})},[deliveries,search]);
  const tp=Math.max(1,Math.ceil(filtered.length/10)),paged=filtered.slice((page-1)*10,page*10);

  const statusBadge=(s:string)=>{const m:any={pending:{bg:'bg-gray-50',text:'text-gray-600',icon:'⏳'},generated:{bg:'bg-blue-50',text:'text-blue-700',icon:'📄'},signed:{bg:'bg-purple-50',text:'text-purple-700',icon:'✍️'},delivered:{bg:'bg-green-50',text:'text-green-700',icon:'✅'},viewed:{bg:'bg-emerald-50',text:'text-emerald-700',icon:'👁'}};const c=m[s]||m.pending;return<span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.bg} ${c.text}`}>{c.icon} {s.charAt(0).toUpperCase()+s.slice(1)}</span>};

  const generateReportCards=async()=>{if(!genForm.term_id)return toast.error('Select a term');setSaving(true);try{const targets=genForm.student_ids.length>0?genForm.student_ids:students.map(s=>s.id);const inserts=targets.map(sid=>({student_id:sid,term_id:genForm.term_id,exam_type_id:genForm.exam_type_id||null,delivery_status:'generated',pdf_generated_at:new Date().toISOString()}));const{error}=await supabase.from('school_report_card_deliveries').upsert(inserts,{onConflict:'student_id,term_id,exam_type_id'});if(error)throw error;toast.success(`✅ ${inserts.length} report cards generated!`);setShowModal('');fetchAll()}catch(e:any){toast.error(e.message)}setSaving(false)};

  const sendDelivery=async(id:number,channel:string)=>{setSaving(true);const upd:any={delivery_status:'delivered'};if(channel==='whatsapp')upd.whatsapp_sent=true;if(channel==='sms')upd.sms_sent=true;if(channel==='email')upd.email_sent=true;const{error}=await supabase.from('school_report_card_deliveries').update(upd).eq('id',id);if(error)toast.error(error.message);else{toast.success(`✅ Sent via ${channel}!`);fetchAll()}setSaving(false)};

  const signReport=async(id:number,role:string)=>{const upd:any={delivery_status:'signed'};if(role==='teacher')upd.teacher_signed_at=new Date().toISOString();if(role==='principal')upd.principal_signed_at=new Date().toISOString();const{error}=await supabase.from('school_report_card_deliveries').update(upd).eq('id',id);if(error)toast.error(error.message);else{toast.success('✅ Signed!');fetchAll()}};

  if(loading)return(<div className="flex flex-col items-center justify-center h-64 gap-3"><div className="w-12 h-12 rounded-2xl flex items-center justify-center text-2xl" style={{background:G.purple}}>📄</div><p className="text-sm font-bold text-gray-500">Loading Digital Delivery…</p></div>);

  return(<div className="animate-fadeIn space-y-5">
    <div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-extrabold text-gray-900" style={{fontFamily:'Outfit,sans-serif',letterSpacing:'-0.03em'}}>📄 Digital Report Card Delivery</h1><p className="text-sm text-gray-500 mt-1">{deliveries.length} deliveries · {deliveries.filter(d=>d.delivery_status==='viewed').length} viewed</p></div><div className="flex items-center gap-2 flex-wrap"><button onClick={fetchAll} className="p-2.5 rounded-xl border border-gray-200 text-gray-400 hover:text-purple-600 transition"><FiRefreshCw size={15}/></button><button onClick={()=>{setGenForm({term_id:0,exam_type_id:0,student_ids:[],channel:'all'});setShowModal('generate')}} className="px-4 py-2.5 rounded-xl text-sm font-bold text-white shadow-md" style={{background:G.purple}}>📄 Generate Cards</button></div></div>

    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[{l:'Generated',v:deliveries.filter(d=>d.delivery_status==='generated').length,e:'📄',c:'#2563eb'},{l:'Signed',v:deliveries.filter(d=>d.delivery_status==='signed').length,e:'✍️',c:'#7c3aed'},{l:'Delivered',v:deliveries.filter(d=>d.delivery_status==='delivered').length,e:'✅',c:'#059669'},{l:'WhatsApp',v:deliveries.filter(d=>d.whatsapp_sent).length,e:'💬',c:'#25d366'},{l:'Viewed',v:deliveries.filter(d=>d.delivery_status==='viewed'||d.parent_viewed).length,e:'👁',c:'#f59e0b'}].map((cd,i)=>(<div key={i} className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm hover:shadow-md transition-all relative overflow-hidden" style={{borderLeftWidth:4,borderLeftColor:cd.c}}><div className="flex items-center justify-between mb-2"><p className="text-[10px] font-bold text-gray-400 tracking-wider uppercase">{cd.l}</p><span className="text-xl">{cd.e}</span></div><p className="text-xl font-extrabold text-gray-900">{cd.v}</p><div className="absolute -bottom-6 -right-6 w-20 h-20 rounded-full opacity-[0.06]" style={{background:cd.c}}/></div>))}</div>

    <div className="flex gap-1 p-1 bg-gray-100 rounded-xl w-fit">{[{k:'deliveries',l:'📋 Deliveries'},{k:'generate',l:'📄 Generate'}].map(t=>(<button key={t.k} onClick={()=>setTab(t.k as any)} className={`px-4 py-2 rounded-lg text-xs font-bold transition-all ${tab===t.k?'bg-white shadow text-purple-700':'text-gray-500 hover:text-gray-700'}`}>{t.l}</button>))}</div>

    {tab==='deliveries'&&<><div className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm"><div className="flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-[220px]"><FiSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search students…" className="w-full pl-10 pr-9 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:bg-white focus:border-purple-300"/>{search&&<button onClick={()=>{setSearch('');setPage(1)}} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-300 hover:text-gray-500"><FiX size={14}/></button>}</div></div></div>
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full border-collapse" style={{fontSize:12}}><thead><tr>{['#','Student','Term','Status','WhatsApp','SMS','Email','Actions'].map((h,i)=><th key={i} className="text-left px-3 py-3 text-[10px] font-bold uppercase tracking-wider whitespace-nowrap" style={{background:'#f8fafc',color:'#475569',borderBottom:'2px solid #e2e8f0'}}>{h}</th>)}</tr></thead>
    <tbody>{paged.map((d,idx)=>{const sn=d.school_students?`${d.school_students.last_name}, ${d.school_students.first_name}`:'-';return(<tr key={d.id} style={{borderBottom:'1px solid #f1f5f9'}} onMouseEnter={e=>(e.currentTarget as HTMLTableRowElement).style.background='#fafbff'} onMouseLeave={e=>(e.currentTarget as HTMLTableRowElement).style.background=''}><td className="px-3 py-3 text-center font-bold text-gray-400">{(page-1)*10+idx+1}</td><td className="px-3 py-3 font-bold text-gray-900">{sn}</td><td className="px-3 py-3 text-gray-600">{d.term_id}</td><td className="px-3 py-3">{statusBadge(d.delivery_status)}</td><td className="px-3 py-3">{d.whatsapp_sent?<FiCheck size={12} className="text-green-500"/>:<span className="text-gray-300">-</span>}</td><td className="px-3 py-3">{d.sms_sent?<FiCheck size={12} className="text-green-500"/>:<span className="text-gray-300">-</span>}</td><td className="px-3 py-3">{d.email_sent?<FiCheck size={12} className="text-green-500"/>:<span className="text-gray-300">-</span>}</td><td className="px-3 py-3"><div className="flex items-center gap-1"><button onClick={()=>signReport(d.id,'teacher')} className="p-1.5 rounded-lg text-purple-400 hover:text-purple-600" title="Teacher Sign"><FiFileText size={11}/></button><button onClick={()=>sendDelivery(d.id,'whatsapp')} className="p-1.5 rounded-lg text-green-400 hover:text-green-600" title="WhatsApp"><FiMessageCircle size={11}/></button><button onClick={()=>sendDelivery(d.id,'sms')} className="p-1.5 rounded-lg text-blue-400 hover:text-blue-600" title="SMS"><FiPhone size={11}/></button><button onClick={()=>sendDelivery(d.id,'email')} className="p-1.5 rounded-lg text-amber-400 hover:text-amber-600" title="Email"><FiMail size={11}/></button></div></td></tr>);})}</tbody></table></div>
    {filtered.length>10&&<div className="px-5 py-3 bg-gray-50 border-t border-gray-100 flex items-center justify-between"><p className="text-xs text-gray-400">Page {page} of {tp}</p><div className="flex items-center gap-1.5"><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} className="p-2 rounded-xl border border-gray-200 text-gray-500 hover:bg-gray-100 disabled:opacity-30"><FiChevronLeft size={14}/></button><button onClick={()=>setPage(p=>Math.min(tp,p+1))} disabled={page===tp} className="p-2 rounded-xl border border-gray-200 text-gray-500 hover:bg-gray-100 disabled:opacity-30"><FiChevronRight size={14}/></button></div></div>}</div></>}

    {tab==='generate'&&<div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm space-y-5"><h3 className="text-lg font-bold text-gray-900">Generate Report Cards</h3><div className="grid grid-cols-2 gap-4"><div><label className="text-xs font-bold text-gray-600 mb-1 block uppercase">Term *</label><select value={genForm.term_id} onChange={e=>setGenForm({...genForm,term_id:Number(e.target.value)})} className="w-full px-3 py-2.5 bg-white border border-gray-200 rounded-xl text-sm focus:outline-none"><option value={0}>Select Term</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name} {t.year}</option>)}</select></div><div><label className="text-xs font-bold text-gray-600 mb-1 block uppercase">Exam Type</label><select value={genForm.exam_type_id} onChange={e=>setGenForm({...genForm,exam_type_id:Number(e.target.value)})} className="w-full px-3 py-2.5 bg-white border border-gray-200 rounded-xl text-sm focus:outline-none"><option value={0}>All Exams</option>{examTypes.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div></div><p className="text-xs text-gray-500">This will generate report cards for all active students. {students.length} students will be processed.</p><button onClick={generateReportCards} disabled={saving} className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold text-white shadow-md" style={{background:G.purple}}>{saving?<div className="spinner" style={{width:14,height:14}}/>:<FiFileText size={14}/>} Generate All Report Cards</button></div>}

    {/* Generate Modal */}
    {showModal==='generate'&&<div className="modal-overlay" onClick={()=>setShowModal('')}><div className="modal-content" style={{maxWidth:500}} onClick={e=>e.stopPropagation()}><div className="px-6 py-5 flex items-center justify-between relative overflow-hidden" style={{background:G.purple}}><div className="absolute right-0 top-0 w-32 h-32 rounded-full -translate-y-10 translate-x-10 opacity-10 bg-white"/><h2 className="text-lg font-bold text-white">📄 Generate Report Cards</h2><button onClick={()=>setShowModal('')} className="p-2 rounded-xl bg-white/20 text-white hover:bg-white/30"><FiX size={18}/></button></div><div className="p-6 space-y-4"><div><label className="text-xs font-bold text-gray-600 mb-1 block uppercase">Term *</label><select value={genForm.term_id} onChange={e=>setGenForm({...genForm,term_id:Number(e.target.value)})} className="w-full px-3 py-2.5 bg-white border border-gray-200 rounded-xl text-sm focus:outline-none"><option value={0}>Select Term</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name} {t.year}</option>)}</select></div><div><label className="text-xs font-bold text-gray-600 mb-1 block uppercase">Exam Type</label><select value={genForm.exam_type_id} onChange={e=>setGenForm({...genForm,exam_type_id:Number(e.target.value)})} className="w-full px-3 py-2.5 bg-white border border-gray-200 rounded-xl text-sm focus:outline-none"><option value={0}>All</option>{examTypes.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div><p className="text-xs text-gray-500">{students.length} students will receive report cards</p></div><div className="p-6 border-t border-gray-100 flex gap-3 justify-end bg-gray-50/50"><button onClick={()=>setShowModal('')} className="btn-outline flex items-center gap-2 text-sm"><FiX size={14}/> Cancel</button><button onClick={generateReportCards} disabled={saving} className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold text-white shadow-md" style={{background:G.purple}}>{saving?<div className="spinner" style={{width:14,height:14}}/>:<FiSend size={14}/>} Generate</button></div></div></div>}
  </div>);
}
