export const dynamic = 'force-dynamic';
import { NextRequest, NextResponse } from 'next/server';

function getSupabase() {
    const { createClient } = require('@supabase/supabase-js');
    return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
}

export async function POST(request: NextRequest) {
    try {
        const supabase = getSupabase();
        const { student_id, letter_type, promotion_history_id } = await request.json();
        if (!student_id || !letter_type) {
            return NextResponse.json({ error: 'student_id and letter_type required' }, { status: 400 });
        }

        // Fetch student
        const { data: student } = await supabase.from('school_students').select('*').eq('id', student_id).single();
        if (!student) return NextResponse.json({ error: 'Student not found' }, { status: 404 });

        // Fetch school details
        const { data: school } = await supabase.from('school_details').select('*').limit(1).single();
        const schoolName = school?.school_name || 'Alpha School';
        const schoolAddr = school?.physical_address || '';
        const schoolPhone = school?.phone1 || '';
        const schoolEmail = school?.email || '';
        const schoolLogo = school?.logo_url || '';

        // Fetch current academic year
        const { data: ay } = await supabase.from('school_academic_years').select('*').eq('is_current', true).limit(1).single();
        const yearName = ay?.year_name || String(new Date().getFullYear());

        const date = new Date().toLocaleDateString('en-KE', { year: 'numeric', month: 'long', day: 'numeric' });
        const admNo = student.admission_no || student.admission_number || 'N/A';
        const studentName = `${student.first_name} ${student.last_name}`;
        const guardianName = student.guardian_name || 'Parent/Guardian';

        const typeLabel = letter_type === 'Promotion' ? 'PROMOTION'
            : letter_type === 'Demotion' ? 'DEMOTION'
            : letter_type === 'Graduation' ? 'GRADUATION'
            : 'TRANSFER';

        const actionWord = letter_type === 'Promotion' ? 'promoted'
            : letter_type === 'Demotion' ? 'demoted'
            : letter_type === 'Graduation' ? 'graduated from'
            : 'transferred from';

        // Fetch form names
        const { data: forms } = await supabase.from('school_forms').select('*');
        const getFormName = (id: number | null) => id ? forms?.find((f: any) => f.id === id)?.form_name || 'N/A' : 'N/A';

        let fromForm = 'N/A';
        let toForm = 'N/A';
        if (promotion_history_id) {
            const { data: hist } = await supabase.from('school_promotion_history').select('*').eq('id', promotion_history_id).single();
            if (hist) {
                fromForm = getFormName(hist.from_form_id);
                toForm = getFormName(hist.to_form_id);
            }
        } else {
            fromForm = getFormName(student.form_id);
        }

        const content = `
${schoolLogo ? `[SCHOOL LOGO]` : ''}${schoolName}
${schoolAddr}
Tel: ${schoolPhone} | Email: ${schoolEmail}

═══════════════════════════════════════════════════════

REF: ${typeLabel}/${yearName}/${admNo}

Date: ${date}

To: ${guardianName}
    Parent/Guardian of ${studentName}
    Adm No: ${admNo}

Dear ${guardianName},

RE: ${typeLabel} OF ${studentName.toUpperCase()}

This is to officially inform you that ${studentName} (Admission Number: ${admNo}) has been ${actionWord} ${toForm !== 'N/A' ? toForm : fromForm} at ${schoolName}.

${letter_type === 'Graduation'
            ? 'We congratulate the student on successful completion of their studies at our institution. We wish them all the best in their future endeavors.'
            : `The student is expected to report to ${toForm} at the beginning of the next academic term. Please ensure all necessary preparations are made in good time.`}

${letter_type === 'Promotion' || letter_type === 'Graduation'
            ? 'We look forward to continued partnership in the student\'s academic journey.'
            : ''}

For any inquiries, please contact the school at ${schoolPhone} or visit the school office.

Yours faithfully,

_____________________
Principal
${schoolName}

═══════════════════════════════════════════════════════
This letter was auto-generated by APSIMS on ${date}
        `.trim();

        // Save letter record
        await supabase.from('school_promotion_letters').insert([{
            student_id,
            promotion_history_id: promotion_history_id || null,
            letter_type,
            academic_year_id: ay?.id || null,
            content,
            generated_by: 'System',
        }]);

        return NextResponse.json({ success: true, content, student_name: studentName, adm_no: admNo });
    } catch (error: any) {
        console.error('[Promotion Letter API] Error:', error);
        return NextResponse.json({ error: error.message || 'Failed to generate letter' }, { status: 500 });
    }
}
